name: flutter_starter_x
description: A CLI tool to bootstrap Flutter projects with packages, folder structures, etc.
version: 1.0.0
repository: https://github.com/imshibl/flutter_starter_x

environment:
  sdk: ^3.7.2


executables:
  flutter-starter-x: flutter_starter_x

dependencies:
  prompts: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
